// AUTO-GENERATED by scripts/glyphs.ts (prebuild hook) — do not edit.
// Maps glyph name → inner SVG markup of Anthony's drawn glyph exported to
// docs/glyphs-import/{name}.svg. Empty until SVGs are dropped in; the Glyph
// primitive falls back to its placeholder paths for any name not present
// here. Names match the atlas/Figma library 1:1, so this is a pure drop-in.
export const IMPORTED_GLYPHS: Record<string, string> = {};
