// AUTO-GENERATED by scripts/glyphs.ts (prebuild hook) — do not edit.
// Drawn glyphs from docs/glyphs-import/, normalized (viewBox 24, currentColor).
// Empty until SVGs land; Glyph falls back to placeholder paths for any name
// not present here. Names match GlyphName 1:1 so it is a pure drop-in.
export const IMPORTED_GLYPHS: Record<string, string> = {};
