// ROUND 47/48/55: glyph import pipeline. Reads docs/glyphs-import/, normalizes
// each drawn SVG, and writes the inner markup into glyphs.generated.ts; the
// Glyph primitive prefers a drawn glyph over its placeholder (drop-in, no atlas
// regen). Runs in the prebuild hook.
//
// Naming (round 55): files are `glyph.{name}.svg` (the library-icon name) — the
// leading `glyph.` prefix is stripped to the bare GlyphName key so a pulled SVG
// wires to its render sites. Plain `{name}.svg` also works. Non-SVG files and
// non-conforming names are skipped and reported, not silently dropped.
// Normalize: viewBox → 0 0 24 24 (scale his artboard if different), hex
// fills/strokes → currentColor (keeps `none`), strip xml/doctype.

import { readdirSync, readFileSync, writeFileSync, existsSync, mkdirSync } from 'fs';
import { join } from 'path';

const ROOT = join(__dirname, '..');
const IMPORT_DIR = join(ROOT, 'docs', 'glyphs-import');
const OUT = join(ROOT, 'src', 'components', 'glyphs.generated.ts');

mkdirSync(IMPORT_DIR, { recursive: true });

const map: Record<string, string> = {};
const skipped: { file: string; reason: string }[] = [];

function keyFromFile(file: string): string {
  return file.replace(/\.svg$/i, '').replace(/^glyph[./]/, ''); // glyph.calendar.svg → calendar
}

function normalize(raw: string): string {
  // viewBox → 0 0 24 24 (wrap inner in a scale transform if his artboard differs)
  const vb = raw.match(/viewBox\s*=\s*["']([-\d.]+)\s+([-\d.]+)\s+([-\d.]+)\s+([-\d.]+)["']/i);
  let inner = raw
    .replace(/<\?xml[\s\S]*?\?>/gi, '')
    .replace(/<!DOCTYPE[\s\S]*?>/gi, '')
    .replace(/<svg[^>]*>/i, '')
    .replace(/<\/svg>\s*$/i, '')
    .trim();
  // ROUND 83: ANY fill/stroke → currentColor (preserve `none`), so a drawn glyph
  // always inherits the `color` prop. The old regex only caught HEX, so a literal
  // fill="white" (what these exports use) survived and the glyph rendered white
  // regardless of color — the wave-glyph greying never took (rounds 79/81).
  inner = inner.replace(/(fill|stroke)\s*=\s*["'](?!none["'])[^"']*["']/gi, '$1="currentColor"');
  if (vb) {
    const [, x, y, w, h] = vb.map(Number) as unknown as number[];
    if (Number(w) !== 24 || Number(h) !== 24 || Number(x) !== 0 || Number(y) !== 0) {
      // ROUND 69 — UNIFORM scale (preserve aspect ratio), then center in 24×24.
      // The old per-axis `scale(24/w 24/h)` squeezed non-square art (e.g. the
      // 40×29 wave → 0.60×0.83, cramped horizontally). One scale factor =
      // 24/max(w,h) keeps the glyph's natural proportions; the leftover space on
      // the short axis is centered so the art is never stretched on one axis.
      const s = 24 / Math.max(Number(w), Number(h));
      const tx = ((24 - Number(w) * s) / 2).toFixed(4);
      const ty = ((24 - Number(h) * s) / 2).toFixed(4);
      inner = `<g transform="translate(${tx} ${ty}) scale(${s.toFixed(4)}) translate(${(-Number(x)).toFixed(4)} ${(-Number(y)).toFixed(4)})">${inner}</g>`;
    }
  }
  return inner;
}

if (existsSync(IMPORT_DIR)) {
  for (const file of readdirSync(IMPORT_DIR)) {
    if (file === 'README.md') continue;
    if (!file.toLowerCase().endsWith('.svg')) {
      skipped.push({ file, reason: 'not an SVG (vector required; raster can\'t be normalized to currentColor/viewBox)' });
      continue;
    }
    const key = keyFromFile(file);
    if (!/^[a-zA-Z][\w.-]*$/.test(key)) {
      skipped.push({ file, reason: 'name off-convention — use glyph.{name}.svg (dots, not slashes/dashes)' });
      continue;
    }
    map[key] = normalize(readFileSync(join(IMPORT_DIR, file), 'utf8'));
  }
}

writeFileSync(OUT, `// AUTO-GENERATED by scripts/glyphs.ts (prebuild hook) — do not edit.
// Drawn glyphs from docs/glyphs-import/, normalized (viewBox 24, currentColor).
// Empty until SVGs land; Glyph falls back to placeholder paths for any name
// not present here. Names match GlyphName 1:1 so it is a pure drop-in.
export const IMPORTED_GLYPHS: Record<string, string> = ${JSON.stringify(map, null, 2)};
`);

const landed = Object.keys(map);
console.log(`glyphs.generated.ts: ${landed.length} imported${landed.length ? ' — ' + landed.join(', ') : ' (placeholders in use)'}`);
for (const s of skipped) console.log(`  SKIP ${s.file}: ${s.reason}`);
