// ROUND 47: glyph import pipeline. Scans docs/glyphs-import/{name}.svg —
// Anthony's drawn glyphs exported from Figma, named exactly per the atlas
// (wind.svg, route.svg, chart.fleet.svg, …) — and writes the inner markup
// into src/components/glyphs.generated.ts. The Glyph primitive prefers these
// over its placeholder paths. Drop-in: names already match, so no atlas
// regeneration and no code changes are needed — just re-run the build.
// Runs in the prebuild hook (before atlas.ts).

import { readdirSync, readFileSync, writeFileSync, existsSync, mkdirSync } from 'fs';
import { join } from 'path';

const ROOT = join(__dirname, '..');
const IMPORT_DIR = join(ROOT, 'docs', 'glyphs-import');
const OUT = join(ROOT, 'src', 'components', 'glyphs.generated.ts');

mkdirSync(IMPORT_DIR, { recursive: true });

const map: Record<string, string> = {};
if (existsSync(IMPORT_DIR)) {
  for (const file of readdirSync(IMPORT_DIR)) {
    if (!file.endsWith('.svg')) continue;
    const name = file.slice(0, -4); // strip .svg → glyph name (matches atlas)
    const raw = readFileSync(join(IMPORT_DIR, file), 'utf8');
    // keep only the inner markup (drop the outer <svg …> wrapper + xml decl)
    const inner = raw
      .replace(/<\?xml[\s\S]*?\?>/g, '')
      .replace(/<svg[^>]*>/i, '')
      .replace(/<\/svg>\s*$/i, '')
      .trim();
    map[name] = inner;
  }
}

const body = `// AUTO-GENERATED by scripts/glyphs.ts (prebuild hook) — do not edit.
// Maps glyph name → inner SVG markup of Anthony's drawn glyph exported to
// docs/glyphs-import/{name}.svg. Empty until SVGs are dropped in; the Glyph
// primitive falls back to its placeholder paths for any name not present
// here. Names match the atlas/Figma library 1:1, so this is a pure drop-in.
export const IMPORTED_GLYPHS: Record<string, string> = ${JSON.stringify(map, null, 2)};
`;
writeFileSync(OUT, body);
console.log(`glyphs.generated.ts: ${Object.keys(map).length} imported glyph(s)${Object.keys(map).length ? ' — ' + Object.keys(map).join(', ') : ' (placeholders in use)'}`);
